'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('cvs', [
      {
        userID: 1,
        fullName: 'Ngô Thanh Đô',
        email: 'thanhdo062305@gmail.com',
        phoneNumber: '0981321319',
        birthDay: '2005-06-23',
        genderID: 'M',
        address: 'Thủ Đức, TP.HCM',
        schoolName: 'Cao Đẳng Công Nghệ Thủ Đức',
        major: 'Công nghệ thông tin',
        degreeID: 'D2',
        gpa: 3.5,
        graduationYear: 2026,
        statusCv: 'CV1',
        submission_date: new Date('2025-06-10'),
        career_objective: 'Trở thành lập trình viên web fullstack',
        archivement: 'Học Bổng 2023-2024',
        references: 'GVHD: Phan Thanh Nhuần',
        batchID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userID: 2,
        fullName: 'Trần Văn B',
        email: 'tranvanb@example.com',
        phoneNumber: '0908123456',
        birthDay: '2004-10-12',
        genderID: 'M',
        address: 'Quận 1, TP.HCM',
        schoolName: 'Đại học Công Nghệ TP.HCM',
        major: 'Kỹ thuật phần mềm',
        degreeID: 'D1',
        gpa: 3.2,
        graduationYear: 2025,
        statusCv: 'CV2', // Đang xem xét
        submission_date: new Date('2025-06-11'),
        career_objective: 'Làm việc tại công ty outsourcing lớn',
        archivement: 'Top 10 HCMUTE Hackathon',
        references: 'GV: TS. Lê Thị C',
        batchID: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userID: 3,
        fullName: 'Lê Thị C',
        email: 'c.le@example.com',
        phoneNumber: '0912345678',
        birthDay: '2003-05-08',
        genderID: 'F',
        address: 'Gò Vấp, TP.HCM',
        schoolName: 'Đại học Khoa học Tự nhiên',
        major: 'Khoa học máy tính',
        degreeID: 'D3', // Bằng Thạc sĩ
        gpa: 3.8,
        graduationYear: 2024,
        statusCv: 'CV1', // Đạt yêu cầu
        submission_date: new Date('2025-06-09'),
        career_objective: 'Chuyên gia AI trong tương lai',
        archivement: 'Học bổng toàn phần Samsung',
        references: 'GV: PGS.TS. Nguyễn Thị Hồng',
        batchID: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userID: 4,
        fullName: 'Phạm Minh D',
        email: 'minhd@example.com',
        phoneNumber: '0909555666',
        birthDay: '2005-11-22',
        genderID: 'M',
        address: 'Tân Phú, TP.HCM',
        schoolName: 'Đại học Công nghiệp TP.HCM',
        major: 'Hệ thống thông tin',
        degreeID: 'D1',
        gpa: 2.9,
        graduationYear: 2025,
        statusCv: 'CV3',
        submission_date: new Date('2025-06-08'),
        career_objective: 'Dev backend tại FPT Software',
        archivement: 'Giải khuyến khích IoT 2024',
        references: 'GV: ThS. Võ Văn Z',
        batchID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userID: 5,
        fullName: 'Nguyễn Ngọc E',
        email: 'ngoc.e@example.com',
        phoneNumber: '0933999444',
        birthDay: '2004-01-30',
        genderID: 'F',
        address: 'Bình Thạnh, TP.HCM',
        schoolName: 'Đại học Sư phạm Kỹ thuật TP.HCM',
        major: 'Công nghệ phần mềm',
        degreeID: 'D1',
        gpa: 3.6,
        graduationYear: 2025,
        statusCv: 'CV4',
        submission_date: new Date('2025-06-10'),
        career_objective: 'UI/UX Designer chuyên nghiệp',
        archivement: 'UX Hackathon HCM 2024 - Giải nhất',
        references: 'GV: TS. Phạm Bảo Khoa',
        batchID: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('cvs', null, {});
  }
};
